# Generated by Django 5.0.7 on 2024-07-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='source_text',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='translated_text',
            new_name='text_ru',
        ),
    ]
