# Generated by Django 5.0.7 on 2024-07-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_rename_source_text_translation_text_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='text_en',
            new_name='en',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='text_ru',
            new_name='ru',
        ),
    ]
